name: simple echo workflow
on: [push]
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Hello, world!"
      - name: Multi-line echo
        run: |
          echo "This is the first line"
          echo "This is the second line"
